BACKUP DATABASE [BD] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\BD.bak' WITH NOFORMAT, NOINIT,  NAME = N'BD-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
